apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: server
        image: cvitoybamp/frontend-otus:1.0.0
