apiVersion: v1 # Версия API
kind: Pod # Объект, который создаем
metadata:
  name: web
  labels: # Метки в формате key: value
    app: web
spec: # Описание Pod
  containers: # Описание контейнеров внутри Pod
  - name: web-app
    image: cvitoybamp/otus.hw1:3.2.0
    volumeMounts:
    - name: app
      mountPath: /app
  initContainers:
  - name: web-app-init
    image: busybox:1.36
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
    - name: app
      mountPath: /app
  volumes:
  - name: app
    emptyDir: {}

 
